# docker-compose.yml
redis:
    image: redis
    container_name: redis_backend
    expose:
      - 6379
node:
    container_name: node_backend
    build: ./
    volumes:
      - ./:/var/www/node
    ports:
      - 3000:3000
    links: 
      - redis
    command:
      sh -c 'npm i && npm run dev'  